
BBBP:
  batch_size: 64
  lr: 1e-4
  min_epochs: 40
  patience: 15
  lr_multiplier: 1
  unet_decay: 1e-4
  task: cls
  monitor: roc

bace:
  batch_size: 64
  lr: 1e-5
  min_epochs: 40
  patience: 15
  lr_multiplier: 1
  unet_decay: 1e-4
  task: cls
  monitor: roc

clintox:
  batch_size: 64
  lr: 1e-4
  min_epochs: 40
  patience: 15
  lr_multiplier: 0.5
  unet_decay: 1e-2
  task: cls
  monitor: roc

sider:
  batch_size: 64
  lr: 1e-4
  min_epochs: 60
  patience: 15
  lr_multiplier: 0.1
  unet_decay: 1e-2
  task: cls
  monitor: roc

tox21:
  batch_size: 128
  lr: 1e-4
  min_epochs: 40
  patience: 15
  lr_multiplier: 0.1
  unet_decay: 1e-2
  task: cls
  monitor: roc

freesolv:
  batch_size: 30
  lr: 2e-4
  min_epochs: 60
  patience: 15
  lr_multiplier: 0.1
  unet_decay: 1e-2
  task: reg
  monitor: rmse

Lipophilicity:
  batch_size: 64
  lr: 1e-4
  min_epochs: 60
  patience: 15
  lr_multiplier: 0.5
  unet_decay: 1e-2
  task: reg
  monitor: rmse

esol:
  batch_size: 32
  lr: 1e-4
  min_epochs: 60
  patience: 15
  lr_multiplier: 0.5
  unet_decay: 1e-2
  task: reg
  monitor: rmse

Mutagenicity:
  batch_size: 256
  lr: 1e-4
  min_epochs: 30
  patience: 15
  lr_multiplier: 0.5
  unet_decay: 1e-2
  task: cls
  monitor: roc

covid:
  batch_size: 256
  lr: 1e-4
  min_epochs: 30
  patience: 15
  lr_multiplier: 0.5
  unet_decay: 1e-2
  task: cls
  monitor: roc

clintox_tdc:
  batch_size: 64
  lr: 1e-4
  min_epochs: 40
  patience: 15
  lr_multiplier: 0.5
  unet_decay: 1e-2
  task: cls
  monitor: roc

ld50:
  batch_size: 256
  lr: 1e-4
  min_epochs: 40
  patience: 15
  lr_multiplier: 0.5
  unet_decay: 1e-2
  task: reg
  monitor: rmse




















































